### ISSUE TITLE
where is `representjs`

### ISSUE THREAD

**Issue by happygirlzt** [ZZR0/ISSTA22-CodeStudy#2]
Hi there, thank you very much for open sourcing!
I was trying to run `PLBart`, however, I did not find the `representjs` file.
Besides, I saw two folders for `PLBart`. I run the `PLBart` under the `Task` folder, should I run the `PLBart` folder instead?
Thank you very much in advance!

<img width="1038" alt="Screenshot 2022-08-09 at 19 52 00" src="https://user-images.githubusercontent.com/15061984/183640956-53c8cd06-c7ed-4859-b0fc-8cd9d5878470.png">

**Comment by ZZR0** [comment]
Sorry for the late response and the mistake in this issue. `representjs` is the package name of `contracode`. Therefore, you should first `cd contracode`, then `pip install -e "."` to install `representjs` to your python environment.

**Comment by happygirlzt** [comment]
Hi @ZZR0, thank you for the reply. However, I found I cannot install the packages by `pip install -e "."` under the `Task/Code-Refinement/contracode/` folder.
<img width="889" alt="Screenshot 2022-08-15 at 13 27 32" src="https://user-images.githubusercontent.com/15061984/184581227-7b979c47-a0be-47eb-bd32-00ba0a2b5c46.png">

**Comment by ZZR0** [comment]
Oh, sorry. You should run `pip install -e "."` under `CodeStudy/contracode` folder.
